import {test,expect} from '@playwright/test';
test('Parcours complet local, calcul, sauvegarde, édition, export, filtres et mode réunion',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByRole('button',{name:'Vue d’ensemble',exact:true}).click();await expect(page.getByRole('heading',{name:'Tableau de bord de l’atelier.'})).toBeVisible();
 await expect(page.locator('.strip-records')).toContainText('63 relevés');
 await page.screenshot({path:'.runtime/dashboard-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Nouvelle saisie'}).click();
 await page.getByLabel('Date de production').fill('2026-10-09');
 await page.getByLabel('Quantité conforme',{exact:true}).fill('5000');
 await page.getByLabel('Rebuts démarrage / réglage',{exact:true}).fill('20');
 await page.getByLabel('Démarrage / arrêt',{exact:true}).fill('30');
 await page.getByLabel('Commentaire du poste').fill('TEST AUTOMATISÉ — contexte isolé');
 await page.screenshot({path:'.runtime/entry-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Enregistrer le relevé'}).click();
 await expect(page.getByRole('status')).toContainText('Relevé enregistré');
 await page.reload();
 await page.getByRole('button',{name:'Historique des relevés',exact:true}).click();
 await page.getByRole('textbox',{name:'Rechercher un relevé'}).fill('TEST AUTOMATISÉ');
 await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'Modifier',exact:true}).click();
 await page.getByLabel('Quantité conforme',{exact:true}).fill('5100');
 await page.getByRole('button',{name:'Enregistrer les modifications'}).click();
 await expect(page.getByRole('status')).toContainText('Relevé enregistré');
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter CSV'}).click();expect((await downloading).suggestedFilename()).toBe('QOS-releves.csv');
 await page.getByRole('button',{name:'Presses & moules',exact:true}).click();
 await page.getByRole('button',{name:'Ajouter une presse'}).click();
 await page.getByLabel('Nom de la presse').fill('TEST-01');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
 await expect(page.getByRole('heading',{name:'TEST-01',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Moules & articles'}).click();await page.getByRole('button',{name:'Ajouter un article'}).click();
 await page.getByLabel('Désignation article').fill('Article test');await page.getByLabel('Code moule / article').fill('TEST-ART');await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Article test',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Vue d’ensemble',exact:true}).click();
 await page.getByLabel('Filtrer par poste').selectOption('Nuit');
 await expect(page.locator('.hero-number')).toHaveText('—');
 await page.getByLabel('Filtrer par poste').selectOption('all');
 await page.getByLabel('Indicateur du graphique').selectOption('dle');
 await page.getByRole('button',{name:'Mode réunion'}).click();await expect(page.locator('.sidebar')).not.toBeVisible();
 await page.keyboard.press('Escape');await expect(page.locator('.sidebar')).toBeVisible();
 expect(errors).toEqual([]);
});
test('Mobile : navigation, formulaire et absence de débordement de page',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.getByRole('button',{name:'Ouvrir le menu'}).click();await page.getByRole('button',{name:'Vue d’ensemble',exact:true}).click();await expect(page.locator('.hero-number')).toBeVisible();
 await page.screenshot({path:'.runtime/dashboard-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Ouvrir le menu'}).click();await page.getByRole('button',{name:'Saisie de production',exact:true}).click();
 await expect(page.getByLabel('Quantité conforme',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'.runtime/entry-mobile.png',fullPage:true});
});
