import React,{useState,useEffect,useRef,useId} from 'react';
import {Activity,ChartNoAxesCombined,Clock3,Maximize2,X,ArrowUpRight,Info,Timer,ChevronRight} from 'lucide-react';
import {ResponsiveContainer,ComposedChart,BarChart,Bar,Line,Cell,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from 'recharts';
import {buildPareto,hourlyUseful,timelineSegments,usefulByShift,clockLabel,STOP_TYPES} from './analytics';
import {calculate,dateLabel,formatNumber as num,SHIFTS} from './domain';
import ShiftOverview from './ShiftOverview';

function ChartFrame({number,title,subtitle,icon:Icon,children,wide=false,tools}){
 const [expanded,setExpanded]=useState(false),dialog=useRef(null);
 useEffect(()=>{if(expanded)dialog.current?.showModal();else dialog.current?.close();},[expanded]);
 const ChartIcon=Icon||({"01":Activity,"02":ChartNoAxesCombined,"03":Timer}[number]);
 const head=<div className="analysis-heading"><div className="analysis-title"><span className="chart-number"><ChartIcon size={23} strokeWidth={1.8}/><small>{number}</small></span><div><span className="eyebrow">{subtitle}</span><h2>{title}</h2></div></div><div className="analysis-actions">{tools}<button type="button" className="icon-button" title={'Agrandir : '+title} aria-label={'Agrandir : '+title} onClick={()=>setExpanded(true)}><Maximize2 size={18}/></button></div></div>;
 return <><section className={`panel analysis-card analysis-${number} ${wide?'analysis-wide':''}`}>{head}{children}</section><dialog ref={dialog} className="chart-dialog" onCancel={()=>setExpanded(false)}><div className="analysis-heading"><div><span className="eyebrow">ATELIER INJECTION / VUE RÉUNION</span><h2>{title}</h2></div><button className="btn" onClick={()=>setExpanded(false)}><X size={17}/>Fermer</button></div>{expanded&&children}</dialog></>;
}
function Timeline({record,onEdit}){
 const [active,setActive]=useState(null),uid=useId().replaceAll(':','');
 useEffect(()=>setActive(null),[record?.id]);
 const segments=timelineSegments(record),c=record?calculate(record):null;
 const width=960,left=84,right=24,end=Number(record?.opening_min)||480;
 const x=m=>left+(width-left-right)*m/end;
 const ticks=Array.from({length:Math.floor(end/60)+1},(_,i)=>i*60);if(ticks.at(-1)!==end)ticks.push(end);
 const d=segments.map((s,i)=>`${i?'L':'M'} ${x(s.start)} ${s.state?52:139} L ${x(s.end)} ${s.state?52:139}`).join(' ');
 const selected=active==null?null:segments[active];
 return <div className="timeline-body"><div className="timeline-facts"><span><i className="legend-run"/>Marche déclarée <strong>{c?num(c.runtime,1):'—'} min</strong></span><span><i className="legend-stop"/>Arrêts <strong>{c?num(record.opening_min-c.runtime,1):'—'} min</strong></span><span className={`journal-state ${segments.length?'complete':''}`}><Timer size={14}/>{segments.length?'Journal complet':'Horaires non renseignés'}</span></div>
 {segments.length?<><div className="timeline-scroll"><svg className="timeline-svg" viewBox="0 0 960 210" role="img" aria-label="Chronologie de marche et d’arrêt reconstituée à partir du journal"><defs><linearGradient id={uid} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#40cdb4" stopOpacity=".22"/><stop offset="100%" stopColor="#40cdb4" stopOpacity=".02"/></linearGradient></defs>{ticks.map(t=><g key={t}><line x1={x(t)} y1="25" x2={x(t)} y2="159" stroke="#e6eef2" strokeDasharray="4 6"/><text x={x(t)} y="189" textAnchor={t===0?'start':t===end?'end':'middle'} fill="#8094a4" fontSize="12">{clockLabel(record.shift_start,t)}</text></g>)}<line x1={left} y1="52" x2={x(end)} y2="52" stroke="#dceae8" strokeDasharray="4 5"/><line x1={left} y1="139" x2={x(end)} y2="139" stroke="#e6eef2"/><text x="0" y="57" fill="#299f8c" fontSize="11">MARCHE</text><text x="0" y="144" fill="#aa8790" fontSize="11">ARRÊT</text><path d={`${d} L ${x(end)} 159 L ${left} 159 Z`} fill={`url(#${uid})`}/><path d={d} stroke="#159d89" strokeWidth="3" strokeLinejoin="round" fill="none"/>{segments.map((s,i)=>s.state===0?<g key={i} role="button" tabIndex={0} aria-label={`${s.label}, de ${clockLabel(record.shift_start,s.start)} à ${clockLabel(record.shift_start,s.end)}, ${num(s.end-s.start,1)} minutes`} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActive(i);}}}><rect x={x(s.start)} y="29" width={Math.max(3,x(s.end)-x(s.start))} height="130" fill={STOP_TYPES[s.category].color} opacity={active===i ? 0.24 : 0.1}/><line x1={x(s.start)} x2={x(s.end)} y1="139" y2="139" stroke={STOP_TYPES[s.category].color} strokeWidth="5"/><circle cx={(x(s.start)+x(s.end))/2} cy="139" r="5" fill={STOP_TYPES[s.category].color}/></g>:null)}</svg></div><div className="timeline-reading">{selected?<><span className="event-swatch" style={{background:STOP_TYPES[selected.category]?.color}}/><strong>{selected.label}</strong><span>{clockLabel(record.shift_start,selected.start)} — {clockLabel(record.shift_start,selected.end)}</span><b>{num(selected.end-selected.start,1)} min</b></>:<><Info size={16}/><span>Survolez ou sélectionnez un arrêt pour afficher sa cause et sa durée.</span></>}</div></>:<ShiftOverview record={record} onEdit={onEdit}/>}
 <div className="analysis-footnote"><span>Le journal donne les horaires ; le bilan présente les durées enregistrées.</span><span>{record?num(record.opening_min/60,1)+' h de relevé':'Aucun relevé'}</span></div></div>;
}
function ParetoTip({active,payload}){if(!active||!payload?.length)return null;const d=payload[0].payload;return <div className="chart-tooltip"><strong>{d.label}</strong><div>Temps d’arrêt <b>{num(d.minutes,1)} min</b></div><div>Part cumulée <b>{num(d.cumulative,1)} %</b></div></div>;}
function UsefulTip({active,payload}){if(!active||!payload?.length)return null;return <div className="chart-tooltip"><strong>{payload[0].payload.label}</strong>{payload.map(p=><div key={p.dataKey}><span>{p.name}</span><b>{num(p.value,1)} min</b></div>)}</div>;}

export default function AnalyticsPanels({rows,data,onEdit}){
 const [selectedId,setSelectedId]=useState(''),[includePlanned,setIncludePlanned]=useState(false),[usefulMode,setUsefulMode]=useState('shift');
 const sorted=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||SHIFTS.indexOf(a.shift)-SHIFTS.indexOf(b.shift));
 const selected=sorted.find(r=>r.id===selectedId)||sorted.find(r=>r.timeline_complete)||sorted[0];
 const pareto=buildPareto(rows,includePlanned),hourly=hourlyUseful(selected),useful=usefulMode==='hour'?hourly:usefulByShift(rows).filter(r=>r.count);
 const displayItems=pareto.items.length<=8?pareto.items:[...pareto.items.slice(0,7),{rank:8,short:'08',label:`Autres causes (${pareto.items.length-7})`,minutes:pareto.items.slice(7).reduce((n,v)=>n+v.minutes,0),cumulative:100,color:'#92a4b6'}];
 const mainCause=pareto.items[0];
 return <section className="analytics-workspace" aria-label="Analyses de production"><div className="section-divider"><div><span className="section-kicker">ANALYSER POUR AGIR</span><h2>Trois regards sur votre production.</h2></div><span className="analysis-live-label"><span/>Selon les filtres sélectionnés</span></div><div className="analytics-grid">
 <ChartFrame number="01" title="Production & arrêts" subtitle="LE DÉROULÉ DU POSTE" wide tools={null}><div className="timeline-selector"><span>Relevé observé</span><select aria-label="Relevé de la chronologie" value={selected?.id||''} onChange={e=>setSelectedId(e.target.value)}>{!sorted.length&&<option value="">Aucun relevé</option>}{sorted.map(r=><option value={r.id} key={r.id}>{dateLabel(r.date)} {r.date.slice(0,4)} · {r.shift} · {data.presses.find(p=>p.id===r.press_id)?.name} · {data.articles.find(a=>a.id===r.article_id)?.name}{r.timeline_complete?' · journal complet':''}</option>)}</select></div><Timeline record={selected} onEdit={onEdit}/></ChartFrame>
 <ChartFrame number="02" title="Pareto des arrêts machine" subtitle="LES CAUSES PRIORITAIRES"><div className="pareto-summary"><div><strong>{num(pareto.total,1)}<small>min perdues</small></strong><p>{mainCause?`${num(mainCause.share,1)} % : ${mainCause.label}`:'Aucun arrêt dans ce périmètre'}</p></div><label className="mini-checkbox"><input type="checkbox" checked={includePlanned} onChange={e=>setIncludePlanned(e.target.checked)}/>Inclure les arrêts planifiés</label></div>{displayItems.length?<><div className="analysis-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={displayItems} margin={{top:14,right:0,left:0,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e6eef2"/><XAxis dataKey="short" tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#5d778e'}}/><YAxis yAxisId="minutes" width={45} tick={{fontSize:11,fill:'#5d778e'}} tickLine={false} axisLine={false}/><YAxis yAxisId="percent" orientation="right" domain={[0,100]} width={43} tickFormatter={v=>v+'%'} tick={{fontSize:11,fill:'#5d778e'}} tickLine={false} axisLine={false}/><Tooltip content={<ParetoTip/>}/><ReferenceLine yAxisId="percent" y={80} stroke="#9eacb9" strokeDasharray="4 6"/><Bar yAxisId="minutes" dataKey="minutes" name="Arrêts" maxBarSize={60} radius={[7,7,2,2]} isAnimationActive={false}>{displayItems.map((d,i)=><Cell key={i} fill={i===0?'#2375e5':'#4fc9af'}/>)}</Bar><Line yAxisId="percent" dataKey="cumulative" name="Cumul" stroke="#06a77b" strokeWidth={2.5} dot={{r:4,fill:'#fff',strokeWidth:2}} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><div className="pareto-legend"><span><i/>Durée (min)</span><span><i/>Cumul (%)</span><span>Seuil repère : 80 %</span></div><ol className="cause-ranking">{pareto.items.map(item=><li key={item.category+'-'+item.label}><span className="cause-rank">{String(item.rank).padStart(2,'0')}</span><span className="cause-name">{item.label}<small>{STOP_TYPES[item.category].label}</small></span><strong>{num(item.minutes,1)} min</strong><span>{num(item.cumulative,1)} %</span></li>)}</ol></>:<div className="analysis-empty"><ChartNoAxesCombined size={30}/><p>Aucun arrêt à classer.</p></div>}<div className="analysis-footnote">{pareto.detailed} / {rows.length} relevés détaillés · les autres sont classés par catégorie. Chaque minute est comptée une seule fois.</div></ChartFrame>
 <ChartFrame number="03" title="Temps utile de production" subtitle="LES MINUTES QUI PRODUISENT"><div className="useful-controls"><div className="segmented"><button className={usefulMode==='shift'?'selected':''} onClick={()=>setUsefulMode('shift')}>Par poste</button><button className={usefulMode==='hour'?'selected':''} onClick={()=>setUsefulMode('hour')}>Par heure</button></div><span>{usefulMode==='hour'?'Relevé observé ci-dessus':'Tous les relevés filtrés'}</span></div>{useful.length?<><div className="analysis-chart useful-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={useful} margin={{top:15,right:12,left:0,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#e6eef2"/><XAxis dataKey="label" tick={{fontSize:11,fill:'#5d778e'}} axisLine={false} tickLine={false}/><YAxis width={49} tick={{fontSize:11,fill:'#5d778e'}} axisLine={false} tickLine={false}/><Tooltip content={<UsefulTip/>}/><Bar stackId="time" dataKey="useful" name="Temps utile" fill="#23b89e" maxBarSize={62} isAnimationActive={false}/><Bar stackId="time" dataKey="lost" name="Arrêts" fill="#67b8ed" maxBarSize={62} radius={usefulMode==='hour'?[5,5,0,0]:[0,0,0,0]} isAnimationActive={false}/>{usefulMode==='shift'&&<Bar stackId="time" dataKey="planned" name="Planifié" fill="#d4e9f3" radius={[5,5,0,0]} maxBarSize={62} isAnimationActive={false}/>}</BarChart></ResponsiveContainer></div><div className="useful-legend"><span><i/>Temps utile</span><span><i/>Arrêts</span>{usefulMode==='shift'&&<span><i/>Planifiés</span>}</div><div className="useful-total"><span><Clock3 size={19}/>Temps machine disponible</span><strong>{num(useful.reduce((s,r)=>s+r.useful,0)/60,1)}<small>h</small></strong></div></>:<div className="analysis-empty"><Timer size={32}/><h3>Le détail horaire attend son journal.</h3><p>Complétez les arrêts du relevé choisi dans le graphique 01.</p>{selected&&onEdit&&<button className="btn" onClick={()=>onEdit(selected)}>Renseigner les horaires</button>}</div>}<div className="analysis-footnote">Temps utile = temps machine, après tous les arrêts. {usefulMode==='hour'?'Découpage en tranches de 60 min depuis le début du relevé.':'Cumul de minutes-machine ; plusieurs presses peuvent dépasser la durée d’un seul poste.'}</div></ChartFrame>
 </div><details className="analysis-method"><summary><Info size={16}/>Comment ces trois graphiques sont-ils calculés ?</summary><div><p><strong>01 — Chronologie.</strong> Chaque arrêt possède un début, une fin et une cause. La courbe descend pendant l’arrêt et remonte à la reprise. Aucun horaire n’est déduit des anciens totaux.</p><p><strong>02 — Pareto.</strong> Les minutes sont regroupées par cause, triées de la plus importante à la plus faible ; la ligne indique le pourcentage cumulé. Les totaux anciens servent de catégories générales.</p><p><strong>03 — Temps utile.</strong> Par poste : ouverture moins tous les arrêts. Par heure : intersection de chaque intervalle de marche avec la tranche horaire. Il s’agit du temps machine, distinct du temps net théorique des pièces conformes.</p></div></details></section>;
}
