import React, { useEffect, useState } from 'react';
import { Activity, LayoutDashboard, ClipboardPenLine, History, Factory, Settings2, ChevronRight, Plus, Monitor, Download, RefreshCw, LogOut, Database, X, AlertCircle, Check, Menu, ArrowUpRight, FileSpreadsheet, SlidersHorizontal } from 'lucide-react';
import { configured, configError, supabase, loadData, download } from './data';
import { SHIFTS, calculate, percent, formatNumber as num, dateLabel, today } from './domain';
import Dashboard from './Dashboard';
import Entry from './Entry';
import References from './References';
import PressScene from './PressScene';
import DailyReview from './DailyReview';
import { yesterday } from './daily';

const sections=[['daily','Bilan J−1',History],['dashboard','Vue d’ensemble',LayoutDashboard],['entry','Saisie de production',ClipboardPenLine],['history','Historique des relevés',History],['references','Presses & moules',Factory],['settings','Configuration',Settings2]];
const titles={daily:['La veille, presse par presse.','Bilan journalier de l’atelier'],dashboard:['La performance, en perspective.','Tableau de bord de l’atelier'],entry:['Chaque poste compte.','Saisie de production'],history:['La mémoire de votre atelier.','Historique des relevés'],references:['Un atelier bien référencé.','Presses & moules'],settings:['Votre espace de travail.','Configuration']};
export function IconButton({children,label,...props}){return <button type="button" className="icon-button" aria-label={label} title={label} {...props}>{children}</button>;}
export function Empty({title='Aucun relevé sur cette période',text='Modifiez les filtres ou ajoutez une saisie de production.',children}){return <div className="empty"><div className="empty-icon"><ClipboardPenLine size={28}/></div><h3>{title}</h3><p>{text}</p>{children}</div>;}
export function Badge({value,target=.85}){return <span className={`badge ${value==null?'neutral':value>1?'warning':value>=target?'success':'warning'}`}>{value==null?'Non calculable':value>1?'À vérifier':value>=target?'Objectif atteint':'Sous objectif'}</span>;}
export function exportCSV(rows,data){
  const headers=['Date','Poste','Presse','Code moule','Article','Ouverture (min)','Arrêts planifiés (min)','Temps requis (min)','Pannes (min)','Démarrage/arrêt (min)','Changement moule (min)','Temps machine (min)','Quantité totale','Conformes','Rebuts démarrage','Rebuts production','Cycle (s/pièce)','Disponibilité (%)','Performance (%)','Qualité (%)','TRS (%)','Standard (s)','Heures dépensées','Recette (h)','DLE (%)','Commentaire','Début du relevé','Journal complet','Arrêts horodatés (JSON)'];
  const safe=v=>{let s=v==null?'':String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
  const pct=v=>v==null?'':(v*100).toFixed(4).replace('.',',');
  const lines=rows.map(r=>{const c=calculate(r),a=data.articles.find(x=>x.id===r.article_id);return [r.date,r.shift,data.presses.find(x=>x.id===r.press_id)?.name,a?.code,a?.name,r.opening_min,r.planned_min,c.required,r.breakdown_min,r.startup_min,r.changeover_min,c.runtime,c.total,r.good_qty,r.startup_rejects,r.production_rejects,r.cycle_seconds,c.availability,c.performance,c.quality,c.trs,r.standard_seconds,r.labor_hours,c.earned,c.dle,r.notes,r.shift_start||'',r.timeline_complete?'Oui':'Non',JSON.stringify(r.stop_events||[])].map((v,i)=>safe([17,18,19,20,24].includes(i)?pct(v):typeof v==='number'?String(v).replace('.',','):v)).join(';');});
  download('QOS-releves.csv','\uFEFF'+[headers.map(safe).join(';'),...lines].join('\r\n'),'text/csv;charset=utf-8');
}
function Login(){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const {error}=await supabase.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});if(error)throw error;}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <main className="login"><div className="login-art"><div className="brand"><span className="brand-mark"><Activity/></span>QOS<span className="brand-divider">/</span>INJECTION</div><h1>Les bonnes données.<br/>Les bonnes décisions.</h1><p>Un espace partagé pour suivre la production et faire progresser votre atelier.</p><PressScene/><span className="eyebrow">PILOTAGE INDUSTRIEL · TRS & DLE</span></div><form className="login-form" onSubmit={submit}><span className="eyebrow">VOTRE ATELIER, CONNECTÉ</span><h2>Heureux de vous retrouver.</h2><p>Connectez-vous avec votre compte atelier.</p><label>Adresse e-mail<input type="email" name="email" autoComplete="username" required/></label><label>Mot de passe<input type="password" name="password" autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Connexion…':'Se connecter'}<ArrowUpRight size={18}/></button><small>Votre responsable doit créer votre compte et vous autoriser à accéder à l’atelier.</small></form></main>;
}
export default function App(){
  const [session,setSession]=useState(undefined),[role,setRole]=useState(configured?null:'admin');
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState('daily'),[editing,setEditing]=useState(null),[notice,setNotice]=useState(''),[meeting,setMeeting]=useState(false),[menu,setMenu]=useState(false);
  const [dailyDate,setDailyDate]=useState(yesterday),[entryDefaults,setEntryDefaults]=useState({}),[returnPage,setReturnPage]=useState('history');
  useEffect(()=>{
    let previous=yesterday();
    const rollover=()=>{const next=yesterday();if(next!==previous){setDailyDate(date=>date===previous?next:date);previous=next;}};
    const timer=setInterval(rollover,60000);window.addEventListener('focus',rollover);
    return()=>{clearInterval(timer);window.removeEventListener('focus',rollover);};
  },[]);
  const [filters,setFilters]=useState({from:'',to:'',press:'all',shift:'all'});
  const [target,setTarget]=useState(()=>{const n=Number(localStorage.getItem('qos-target')??85);return Number.isFinite(n)&&n>0&&n<=100?n:85;});
  useEffect(()=>{if(!supabase){setSession(null);return;}supabase.auth.getSession().then(({data,error})=>{if(error)setError(error.message);setSession(data.session);});const {data:sub}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>sub.subscription.unsubscribe();},[]);
  async function refresh(){setBusy(true);try{if(supabase){const {data:member,error}=await supabase.from('workshop_members').select('role').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(!member)throw new Error('Votre compte n’est pas encore autorisé. Ajoutez-le à workshop_members dans Supabase.');setRole(member.role);}const next=await loadData();setData(next);setError('');const dates=next.records.map(r=>r.date).sort();setFilters(f=>({...f,from:f.from||dates[0]||today(),to:f.to||dates.at(-1)||today()}));}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{if(session!==undefined&&(!configured||session))refresh();else setData(null);},[session?.user?.id,session===undefined]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{const key=e=>{if(e.key==='Escape'){setMeeting(false);setMenu(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  function go(p){setPage(p);setMenu(false);setMeeting(false);if(p==='entry'){setEditing(null);setEntryDefaults({});setReturnPage('history');}}
  const canWrite=role==='admin'||role==='operator';
  if(configError)return <div className="fatal"><AlertCircle/><h1>Configuration à compléter</h1><p>{configError}</p></div>;
  if(session===undefined)return <div className="loading"><Activity className="pulse"/>Ouverture de l’atelier…</div>;
  if(configured&&!session)return <Login/>;
  const filtered=data?.records.filter(r=>(!filters.from||r.date>=filters.from)&&(!filters.to||r.date<=filters.to)&&(filters.press==='all'||r.press_id===filters.press)&&(filters.shift==='all'||r.shift===filters.shift))||[];
  const edit=r=>{setEditing(r);setReturnPage(page==='daily'?'daily':'history');setPage('entry');setMeeting(false);};
  const newDaily=defaults=>{setEntryDefaults(defaults);setEditing(null);setReturnPage('daily');setPage('entry');setMeeting(false);};
  return <div className={`app ${meeting?'meeting':''}`}>
    {menu&&<button className="menu-overlay" aria-label="Fermer le menu" onClick={()=>setMenu(false)}/>}
    <aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('daily');}}><span className="brand-mark"><Activity size={24}/></span><span>QOS<span className="brand-dot">.</span></span></a><div className="workspace"><div className="workspace-icon"><Factory size={20}/></div><div><strong>Atelier Injection</strong><small>Espace de production</small></div><ChevronRight size={15}/></div><p className="nav-label">PILOTAGE DE L’ATELIER</p><nav>{sections.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>go(key)}><Icon size={19}/>{label}{page===key&&<span className="nav-active"/>}</button>)}</nav><div className="sidebar-insight"><span className="tiny-symbol">↗</span><strong>De la mesure<br/>à l’amélioration.</strong><p>Chaque relevé éclaire la performance de l’atelier.</p><div className="mini-bars">{[25,42,35,58,49,70,85,100].map((h,i)=><span key={i} style={{height:h+'%'}}/>)}</div></div><div className="sidebar-bottom"><div className="avatar">{configured?'AT':'QL'}</div><div><strong>{configured?'Équipe atelier':'Espace local'}</strong><small>{configured?(role==='admin'?'Administrateur':role==='operator'?'Opérateur':'Consultation'):'Données sur cet appareil'}</small></div>{supabase&&<IconButton label="Se déconnecter" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/></IconButton>}</div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumb"><IconButton label="Ouvrir le menu" onClick={()=>setMenu(true)}><Menu size={19}/></IconButton><span>Atelier Injection</span><ChevronRight size={14}/><strong>{sections.find(s=>s[0]===page)?.[1]}</strong></div><div className="top-actions"><span className={`connection ${configured?'cloud':''}`}><Database size={14}/>{configured?'Supabase connecté':'Mode local'}</span><span className="top-date">{new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</span><div className="avatar light">IN</div></div></header>
      <div className="content"><div className="page-heading"><div><span className="eyebrow">{titles[page][0]}</span><h1>{titles[page][1]}<span className="heading-dot">.</span></h1></div><div className="heading-actions">{['daily','dashboard'].includes(page)&&<button className="btn" onClick={()=>setMeeting(!meeting)}>{meeting?<X size={17}/>:<Monitor size={17}/>} {meeting?'Quitter la réunion':'Mode réunion'}</button>}{canWrite&&page!=='entry'&&<button className="btn primary" onClick={()=>page==='daily'?newDaily({date:dailyDate}):go('entry')}><Plus size={18}/>Nouvelle saisie</button>}</div></div>
      {!configured&&<div className="local-banner"><span><span className="status-dot"/> Données du classeur · sauvegarde dans ce navigateur</span><button onClick={()=>go('settings')}>Configurer le partage <ChevronRight size={14}/></button></div>}
      {error&&<div className="error callout" role="alert"><AlertCircle size={19}/><span>{error}</span><button className="btn" onClick={refresh}>Réessayer</button></div>}
      {!data?<div className="loading"><RefreshCw className="pulse"/>Chargement des données…</div>:<>
      {['dashboard','history'].includes(page)&&<div className="filterbar"><div className="filter-caption"><SlidersHorizontal size={18}/><strong>Périmètre</strong></div><label className="date-filter"><span>Du</span><input aria-label="Date de début" type="date" value={filters.from} max={filters.to} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label className="date-filter"><span>au</span><input aria-label="Date de fin" type="date" value={filters.to} min={filters.from} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><select aria-label="Filtrer par presse" value={filters.press} onChange={e=>setFilters({...filters,press:e.target.value})}><option value="all">Toutes les presses</option>{data.presses.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Filtrer par poste" value={filters.shift} onChange={e=>setFilters({...filters,shift:e.target.value})}><option value="all">Tous les postes</option>{SHIFTS.map(s=><option key={s}>{s}</option>)}</select><IconButton label="Actualiser les données" onClick={refresh} disabled={busy}><RefreshCw size={18} className={busy?'pulse':''}/></IconButton></div>}
      {page==='daily'&&<DailyReview data={data} date={dailyDate} onDateChange={setDailyDate} onEdit={canWrite?edit:undefined} onNew={canWrite?newDaily:undefined} onRefresh={refresh} busy={busy} onExport={rows=>exportCSV(rows,data)}/>}
      {page==='dashboard'&&<Dashboard rows={filtered} data={data} target={target/100} onNew={()=>go('entry')} meeting={meeting} onEdit={canWrite?edit:undefined} onExport={()=>exportCSV(filtered,data)}/>}
      {page==='entry'&&<Entry key={editing?.id||'new'} data={data} editing={editing} defaults={entryDefaults} canWrite={canWrite} onSaved={async()=>{await refresh();setNotice('Relevé enregistré avec succès.');setEditing(null);setPage(returnPage);setFilters(f=>({...f,from:'',to:''}));}}/>}
      {page==='history'&&<HistoryView rows={filtered} data={data} onEdit={edit} canWrite={canWrite} target={target/100}/>}
      {page==='references'&&<References data={data} canEdit={role==='admin'} refresh={refresh} notify={setNotice}/>}
      {page==='settings'&&<Settings data={data} target={target} setTarget={n=>{setTarget(n);localStorage.setItem('qos-target',String(n));}}/>}
      </>}
      <footer className="footer"><span>QOS <span>/</span> ATELIER INJECTION</span><span>Des données utiles. Des décisions concrètes.</span></footer></div>
    </main>{notice&&<div className="toast" role="status"><Check size={19}/>{notice}<IconButton label="Fermer la notification" onClick={()=>setNotice('')}><X size={16}/></IconButton></div>}
  </div>;
}
function HistoryView({rows,data,onEdit,canWrite,target}){
  const [search,setSearch]=useState(''),[page,setPage]=useState(1);
  useEffect(()=>setPage(1),[rows.length,search]);
  const matching=rows.filter(r=>[data.presses.find(p=>p.id===r.press_id)?.name,data.articles.find(a=>a.id===r.article_id)?.name,r.notes].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)||SHIFTS.indexOf(a.shift)-SHIFTS.indexOf(b.shift));
  const max=Math.max(1,Math.ceil(matching.length/15)),current=Math.min(page,max);
  return <section className="panel history-panel"><div className="panel-heading"><div><h2>Tous les relevés <span className="count">{matching.length}</span></h2><p>Retrouvez et corrigez les saisies de votre atelier.</p></div><div className="inline-actions"><input aria-label="Rechercher un relevé" placeholder="Rechercher une presse, un article…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn" onClick={()=>exportCSV(matching,data)} disabled={!matching.length}><Download size={17}/>Exporter CSV</button></div></div>{!matching.length?<Empty/>:<><div className="table-scroll"><table><thead><tr><th>Date / poste</th><th>Presse</th><th>Article</th><th>Conformes</th><th>Rebuts</th><th>TRS</th><th>DLE</th><th>État</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{matching.slice((current-1)*15,current*15).map(r=>{const c=calculate(r),a=data.articles.find(a=>a.id===r.article_id);return <tr key={r.id}><td><strong>{dateLabel(r.date)} {r.date.slice(0,4)}</strong><small>{r.shift}</small></td><td><span className="press-name"><Factory size={16}/>{data.presses.find(p=>p.id===r.press_id)?.name}</span></td><td><strong>{a?.name}</strong><small>{a?.code}</small></td><td>{num(r.good_qty)}</td><td>{num(c.rejects)}</td><td className="numeric-emphasis">{percent(c.trs)}</td><td>{percent(c.dle)}</td><td><Badge value={c.trs} target={target}/></td><td><button className="text-button" onClick={()=>onEdit(r)}>{canWrite?'Modifier':'Consulter'}<ChevronRight size={14}/></button></td></tr>;})}</tbody></table></div><div className="pagination"><span>{matching.length} relevés · {current} / {max}</span><div><button className="btn" disabled={current===1} onClick={()=>setPage(current-1)}>Précédent</button><button className="btn" disabled={current===max} onClick={()=>setPage(current+1)}>Suivant</button></div></div></>}</section>;
}
function Settings({data,target,setTarget}){
 return <div className="settings-grid"><section className="panel settings-card"><Database className="section-icon"/><h2>Sauvegarde & connexion</h2><span className="badge success">{configured?'Base Supabase':'Sauvegarde locale'}</span><p>{configured?'Les relevés sont partagés avec les membres autorisés de l’atelier.':'Les modifications sont conservées uniquement dans ce navigateur. Exportez une sauvegarde avant de changer d’appareil ou de vider les données du navigateur.'}</p><button className="btn primary" onClick={()=>download('QOS-sauvegarde-'+today()+'.json',JSON.stringify({version:1,exported_at:new Date().toISOString(),...data},null,2))}><Download size={17}/>Sauvegarder toutes les données</button><h3>Connexion à Supabase</h3><ol><li>Exécuter <code>supabase/01_schema.sql</code>.</li><li>Importer le classeur avec <code>02_import_excel.sql</code>.</li><li>Ajouter le journal avec <code>03_stop_journal.sql</code>.</li><li>Renforcer les horaires avec <code>04_daily_review.sql</code>.</li><li>Créer les comptes et leurs autorisations.</li><li>Renseigner les deux valeurs du fichier <code>.env</code> et relancer l’application.</li></ol><small>Le guide README détaille la mise en ligne. Les nouvelles saisies locales ne sont pas transférées automatiquement vers Supabase.</small></section><div><section className="panel settings-card"><Settings2 className="section-icon"/><h2>Objectif TRS</h2><p>Seuil d’analyse pour les graphiques et les états. Préférence de ce navigateur ; valeur initiale proposée : 85 %.</p><label className="target-input">Objectif (%)<input type="number" min="1" max="100" step="1" value={target} onChange={e=>{const v=Number(e.target.value);if(v>=1&&v<=100)setTarget(v);}}/></label></section><section className="panel settings-card formula-card"><FileSpreadsheet className="section-icon"/><h2>Une méthode transparente</h2><p>Les calculs par relevé reprennent le classeur. La synthèse utilise les temps et quantités cumulés.</p><dl><dt>Disponibilité</dt><dd>Temps machine ÷ temps requis</dd><dt>Performance</dt><dd>Quantité totale × cycle ÷ temps machine en secondes</dd><dt>Qualité</dt><dd>Quantité conforme ÷ quantité totale</dd><dt>TRS atelier</dt><dd>Σ (conformes × cycle) ÷ Σ temps requis en secondes</dd><dt>DLE</dt><dd>Recette en heures ÷ heures dépensées</dd></dl><small>Les périodes sans temps requis sont non calculables. Les ratios dépassant 100 % sont conservés et signalés. Avec des cycles différents, le produit des trois taux agrégés peut différer du TRS global.</small></section></div></div>;
}
