import React,{useEffect,useState} from 'react';
import { Factory, Clock3, Boxes, Users, LockKeyhole, Save, Check, AlertTriangle, Info, ClipboardPenLine } from 'lucide-react';
import { SHIFTS,calculate,percent,formatNumber as num,today,numericFields,validateRecord,recordKey } from './domain';
import { saveRecord } from './data';
import StopJournal from './StopJournal';
import { defaultStart } from './analytics';
import { overlapError } from './daily';

const defaultRecord=data=>({id:crypto.randomUUID(),date:today(),shift:'Matin',press_id:data.presses.find(p=>p.active)?.id||'',article_id:data.articles.find(a=>a.active)?.id||'',opening_min:480,planned_min:0,breakdown_min:0,startup_min:0,changeover_min:0,good_qty:0,startup_rejects:0,production_rejects:0,labor_hours:8,notes:'',source:'web',source_row:null,shift_start:'06:00',timeline_complete:false,stop_events:[]});
function Field({label,name,value,onChange,unit,integer=false,disabled=false}){return <label className="field"><span>{label}</span><div className="input-unit"><input name={name} aria-label={label} type="number" min="0" step={integer?'1':'any'} required disabled={disabled} value={value} onChange={e=>onChange(name,e.target.value===''?'':Number(e.target.value))}/><span>{unit}</span></div></label>;}
function Auto({label,value,unit}){return <div className="auto-field"><span>{label}<LockKeyhole size={12}/></span><strong>{value}<small>{unit}</small></strong></div>;}
export default function Entry({data,editing,defaults={},canWrite,onSaved}){
 const [r,setR]=useState(()=>editing?{timeline_complete:false,stop_events:[],...editing,shift_start:editing.shift_start||defaultStart(editing.shift)}:{...defaultRecord(data),...defaults,shift_start:defaultStart(defaults.shift||'Matin')});
 const [busy,setBusy]=useState(false),[errors,setErrors]=useState([]),[dirty,setDirty]=useState(false);
 const article=data.articles.find(a=>a.id===r.article_id);
 const sameArticle=editing?.article_id===r.article_id;
 const cycle=sameArticle?editing.cycle_seconds:article?article.mold_cycle_seconds/article.cavities:0;
 const standard=sameArticle?editing.standard_seconds:article?.standard_seconds||0;
 const record={...r,cycle_seconds:cycle,standard_seconds:standard};
 const c=calculate(record);
 const duplicate=data.records.some(x=>x.id!==r.id&&recordKey(x)===recordKey(r));
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 const change=(key,value)=>{setR(prev=>({...prev,[key]:value,...(key==='shift'&&!prev.timeline_complete?{shift_start:defaultStart(value)}:{})}));setDirty(true);};
 async function submit(e){e.preventDefault();const eList=validateRecord(record);const conflict=overlapError(record,data.records);if(conflict)eList.push(conflict);if(duplicate)eList.push('Ce relevé existe déjà. Ouvrez-le dans l’historique pour le modifier.');if(eList.length){setErrors(eList);return;}setBusy(true);setErrors([]);try{await saveRecord(record);setDirty(false);await onSaved();}catch(err){setErrors([err.message]);}finally{setBusy(false);}}
 return <form className="entry-layout" onSubmit={submit}><div className="entry-main"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">01 / CONTEXTE</span><h2>{editing?'Relevé du '+editing.date:'Un nouveau relevé'}</h2></div><span className="badge neutral"><ClipboardPenLine size={13}/>{editing?'Modification':'Saisie manuelle'}</span></div><div className="form-body"><div className="form-grid context-grid"><label className="field"><span>Date de production</span><input type="date" required value={r.date} disabled={!canWrite} onChange={e=>change('date',e.target.value)}/></label><label className="field"><span>Poste</span><select value={r.shift} disabled={!canWrite} onChange={e=>change('shift',e.target.value)}>{SHIFTS.map(s=><option key={s}>{s}</option>)}</select></label><label className="field"><span>Presse</span><select required value={r.press_id} disabled={!canWrite} onChange={e=>change('press_id',e.target.value)}><option value="" disabled>Choisir une presse</option>{data.presses.filter(p=>p.active||p.id===r.press_id).map(p=><option key={p.id} value={p.id}>{p.name}{!p.active?' · archivée':''}</option>)}</select></label><label className="field wide"><span>Code moule / article</span><select required value={r.article_id} disabled={!canWrite} onChange={e=>change('article_id',e.target.value)}><option value="" disabled>Choisir un article</option>{data.articles.filter(a=>a.active||a.id===r.article_id).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}{!a.active?' · archivé':''}</option>)}</select></label><Auto label="Désignation article" value={article?.name||'—'}/></div><p className="field-help"><Info size={14}/>Date du début du poste : une nuit qui finit le lendemain reste rattachée à cette date. Vérifiez l’heure de début du journal.</p><div className="article-detail"><Factory size={16}/>{article?`${article.cavities} empreintes · ${num(article.mold_cycle_seconds,2)} s / cycle moule`:'Ajoutez d’abord un article dans Presses & moules.'}<span>Cycle retenu : {num(cycle,3)} s / pièce</span></div>{duplicate&&<p className="error" role="alert">Un relevé existe déjà pour cette combinaison date, poste, presse et article.</p>}</div></section>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">02 / TEMPS DE PRODUCTION</span><h2>Le temps de votre poste</h2></div><Clock3 size={21} className="muted"/></div><div className="form-body"><div className="form-grid"><Field label="Temps d’ouverture" name="opening_min" value={r.opening_min} onChange={change} unit="min" disabled={!canWrite}/><Field label="Arrêts planifiés" name="planned_min" value={r.planned_min} onChange={change} unit="min" disabled={!canWrite||r.timeline_complete}/><Auto label="Temps requis" value={num(c.required,1)} unit="min"/><Field label="Pannes" name="breakdown_min" value={r.breakdown_min} onChange={change} unit="min" disabled={!canWrite||r.timeline_complete}/><Field label="Démarrage / arrêt" name="startup_min" value={r.startup_min} onChange={change} unit="min" disabled={!canWrite||r.timeline_complete}/><Field label="Changement de moule" name="changeover_min" value={r.changeover_min} onChange={change} unit="min" disabled={!canWrite||r.timeline_complete}/></div><div className="machine-time"><span><Clock3 size={17}/>Temps machine calculé</span><strong>{num(c.runtime,1)} <small>min</small></strong></div></div></section>
 <StopJournal record={r} onChange={next=>{setR(next);setDirty(true);}} disabled={!canWrite}/>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">03 / QUANTITÉS & MAIN-D’ŒUVRE</span><h2>La production réalisée</h2></div><Boxes size={21} className="muted"/></div><div className="form-body"><div className="form-grid"><Field label="Quantité conforme" name="good_qty" value={r.good_qty} onChange={change} unit="pcs" integer disabled={!canWrite}/><Field label="Rebuts démarrage / réglage" name="startup_rejects" value={r.startup_rejects} onChange={change} unit="pcs" integer disabled={!canWrite}/><Field label="Rebuts production" name="production_rejects" value={r.production_rejects} onChange={change} unit="pcs" integer disabled={!canWrite}/><Auto label="Quantité totale" value={num(c.total)} unit="pcs"/><Auto label="Temps standard" value={num(standard,3)} unit="s / pièce"/><Field label="Heures dépensées" name="labor_hours" value={r.labor_hours} onChange={change} unit="h" disabled={!canWrite}/></div><p className="field-help"><Info size={14}/>Les heures dépensées correspondent au temps de main-d’œuvre total affecté à ce relevé.</p><label className="field"><span>Commentaire du poste <small>facultatif</small></span><textarea value={r.notes} maxLength={4000} disabled={!canWrite} onChange={e=>change('notes',e.target.value)} placeholder="Incident, réglage particulier, point à partager en réunion…" rows={3}/></label></div></section></div>
 <aside className="entry-summary"><section className="panel"><div className="summary-top"><span className="eyebrow">CALCUL EN DIRECT</span><h2>Votre poste en un regard</h2><span className="summary-trs">{percent(c.trs)}</span><p>Taux de rendement synthétique</p></div><div className="summary-ratios">{[['Disponibilité',c.availability],['Performance',c.performance],['Qualité',c.quality],['DLE',c.dle]].map(([label,v])=><div key={label}><span>{label}</span><strong>{percent(v)}</strong></div>)}<div><span>Recette</span><strong>{num(c.earned,2)} h</strong></div></div><div className="summary-help"><LockKeyhole size={17}/><p>Les champs gris se calculent automatiquement à chaque modification.</p></div>{c.performance>1&&<div className="entry-warning"><AlertTriangle size={18}/><p>Performance supérieure à 100 %. Vérifiez la quantité et le cycle théorique.</p></div>}{c.required===0&&<div className="entry-warning"><Info size={18}/><p>Poste sans temps requis : le TRS est non calculable.</p></div>}<div className="save-area">{errors.length>0&&<div className="error" role="alert">{errors.map((e,i)=><p key={i}>{e}</p>)}</div>}<button className="btn primary save-button" type="submit" disabled={busy||!canWrite}><Save size={18}/>{busy?'Enregistrement…':editing?'Enregistrer les modifications':'Enregistrer le relevé'}</button><small>{canWrite?(dirty?'Modifications non enregistrées':'Prêt pour votre saisie'):'Accès en consultation uniquement'}</small></div></section><div className="input-legend"><span><i/>Saisie manuelle</span><span><i className="gray"/>Calcul automatique</span></div></aside></form>;
}
